{% set version = "0.3.4" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mlr3tuningspaces
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mlr3tuningspaces_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mlr3tuningspaces/mlr3tuningspaces_{{ version }}.tar.gz
  sha256: eb0b0b1998341039090e02d97e57d1cfc69c9c253f036be23fe91785b6634bd4

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-r6 >=2.5.0
    - r-checkmate >=2.0.0
    - r-data.table >=1.14.0
    - r-mlr3 >=0.11.0
    - r-mlr3misc >=0.9.1
    - r-mlr3tuning >=0.8.0
    - r-paradox >=0.7.1
  run:
    - r-base
    - r-r6 >=2.5.0
    - r-checkmate >=2.0.0
    - r-data.table >=1.14.0
    - r-mlr3 >=0.11.0
    - r-mlr3misc >=0.9.1
    - r-mlr3tuning >=0.8.0
    - r-paradox >=0.7.1

test:
  commands:
    - $R -e "library('mlr3tuningspaces')"           # [not win]
    - "\"%R%\" -e \"library('mlr3tuningspaces')\""  # [win]

about:
  home: https://mlr3tuningspaces.mlr-org.com, https://github.com/mlr-org/mlr3tuningspaces
  license: LGPL-3.0-only
  summary: Collection of search spaces for hyperparameter tuning. Includes various search spaces that can be directly applied on an `mlr3` learner. Additionally, meta information about the search space can be queried.
  license_family: LGPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
